### ISSUE TITLE
Error while reloading game

### ISSUE THREAD

**Issue by rwieland** [rwieland/Othello#15]
simulateOthello(1, '1', '1')
undefined
reloadGame(GAME_LOGS_TEXT[1])
othello.js:119 Uncaught RangeError: Invalid string length
    at Array.toString (native)
    at file:///C:/Users/rwieland/Desktop/Personal/Computer%20Science/Othello/js/othello.js:119:21
    at Array.map (native)
    at Othello.tokenCount (file:///C:/Users/rwieland/Desktop/Personal/Computer%20Science/Othello/js/othello.js:116:28)
    at Othello.scoreboard (file:///C:/Users/rwieland/Desktop/Personal/Computer%20Science/Othello/js/display.js:81:7)
    at Othello.play (file:///C:/Users/rwieland/Desktop/Personal/Computer%20Science/Othello/js/display.js:187:8)
    at reloadGame (file:///C:/Users/rwieland/Desktop/Personal/Computer%20Science/Othello/js/utils.js:140:15)
    at <anonymous>:1:1

**Comment by rwieland** [comment]
Something seems to be appending arrays to the end of the board array. that.barr[i] in tokenCount is shown as just before the error occurs
["0", " ", "0", " ", " ", " ", " ", " ", " ", "0", "0", " ", " ", "1", " ", "0", "1", " ", "0", " ", "1", " ", "0", " ", "0", "1", "0", "1", "0", "0", "0", "0", " ", "0", "1", "0", "0", " ", "0", " ", " ", " ", " ", "1", " ", " ", " ", " ", " ", " ", " ", "1", " ", " ", " ", " ", " ", " ", " ", "1", " ", " ", " ", " ", Array(64), Array(65), Array(66), Array(67), Array(68), Array(69), Array(70), Array(71), Array(72), Array(73), Array(74), Array(75), Array(76), Array(77), Array(78), Array(79), Array(80), Array(81), Array(82), Array(83), Array(84)]
